ERROR 2024-08-21 11:13:53,877 views Catch Key...: question_data_code_22
ERROR 2024-08-21 11:14:00,284 views -----Data From Cache----
ERROR 2024-08-21 11:14:13,202 views -----Data From Database----
ERROR 2024-08-21 11:33:54,721 views Catch Key...: question_data_code_22
ERROR 2024-08-21 11:33:55,996 views -----Data From Cache----
ERROR 2024-08-21 11:56:05,789 views Catch Key...: question_data_code_22
ERROR 2024-08-21 11:56:07,533 views -----Data From Cache----
ERROR 2024-08-21 15:40:39,855 log Internal Server Error: /api/update-is-accept/5/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 7630, in update_is_accept
    candidate.round_of_interview = 'Registered'
    ^^^^^^^^^
NameError: name 'candidate' is not defined. Did you mean: 'candidates'?
ERROR 2024-08-21 15:40:39,979 basehttp "PATCH /api/update-is-accept/5/ HTTP/1.1" 500 99815
ERROR 2024-08-22 12:44:19,340 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-22 12:44:19,847 basehttp "GET /api/course-content/Trainer/?user_name=trainer31 HTTP/1.1" 500 54
ERROR 2024-08-22 12:44:20,807 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-22 12:44:20,875 basehttp "GET /api/course-content/Trainer/?user_name=trainer31 HTTP/1.1" 500 54
ERROR 2024-08-22 19:30:41,849 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-22 19:30:42,205 basehttp "GET /api/course-content/Trainer/?user_name=trainer31 HTTP/1.1" 500 54
ERROR 2024-08-22 19:30:42,562 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-22 19:30:42,565 basehttp "GET /api/course-content/Trainer/?user_name=trainer31 HTTP/1.1" 500 54
ERROR 2024-08-23 00:30:48,480 log Internal Server Error: /api/round-of-interview-count/
ERROR 2024-08-23 00:30:48,579 basehttp "GET /api/round-of-interview-count/?college_id=1&company_name=Wipro HTTP/1.1" 500 5894
ERROR 2024-08-23 13:14:52,590 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-23 13:14:52,998 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 67
ERROR 2024-08-23 13:14:54,697 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-23 13:14:54,703 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 67
ERROR 2024-08-23 13:38:38,076 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-23 13:38:38,452 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 67
ERROR 2024-08-23 13:38:38,758 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-23 13:38:38,761 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 67
ERROR 2024-08-23 13:40:47,465 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-23 13:40:47,589 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 5334
ERROR 2024-08-23 19:30:21,812 log Internal Server Error: /api/upload-screenshot/116
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/upload-screenshot/116/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-08-23 19:30:21,990 basehttp "POST /api/upload-screenshot/116 HTTP/1.1" 500 73742
ERROR 2024-08-23 19:31:10,902 log Internal Server Error: /api/upload-screenshot/116
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/upload-screenshot/116/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-08-23 19:31:11,702 basehttp "POST /api/upload-screenshot/116 HTTP/1.1" 500 73742
ERROR 2024-08-23 19:33:35,527 log Internal Server Error: /api/upload-screenshot/116/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 8201, in upload_screenshot
    instance.test_candidate_id = pk
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "116": "Screenshots.test_candidate_id" must be a "tests_candidates_map" instance.
ERROR 2024-08-23 19:33:35,669 basehttp "POST /api/upload-screenshot/116/ HTTP/1.1" 500 77681
ERROR 2024-08-23 19:34:25,684 log Internal Server Error: /api/upload-screenshot/116/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 8201, in upload_screenshot
    instance.test_candidate_id = pk
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "116": "Screenshots.test_candidate_id" must be a "tests_candidates_map" instance.
ERROR 2024-08-23 19:34:25,918 basehttp "POST /api/upload-screenshot/116/ HTTP/1.1" 500 77681
ERROR 2024-08-23 19:35:15,400 log Internal Server Error: /api/upload-screenshot/116/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 8201, in upload_screenshot
    instance.test_candidate_id = pk
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "116": "Screenshots.test_candidate_id" must be a "tests_candidates_map" instance.
ERROR 2024-08-23 19:35:15,427 basehttp "POST /api/upload-screenshot/116/ HTTP/1.1" 500 77681
ERROR 2024-08-23 22:04:47,375 log Internal Server Error: /api//students/announcement/2/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 8225, in get_student_announcement
    'announcement_image': student_entry.announcement_image.decode('utf-8') if student_entry.announcement_image else None
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'memoryview' object has no attribute 'decode'
ERROR 2024-08-23 22:04:47,516 basehttp "GET /api//students/announcement/2/ HTTP/1.1" 500 100760
ERROR 2024-08-23 23:23:57,643 log Internal Server Error: /api//students/announcement/2/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 8223, in get_student_announcement
    data = list(map(lambda entry: {
                ^^^^^^^^^^^^^^^^^^^
TypeError: 'eligible_student_list' object is not iterable
ERROR 2024-08-23 23:23:58,014 basehttp "GET /api//students/announcement/2/ HTTP/1.1" 500 100506
ERROR 2024-08-24 12:01:52,165 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-24 12:01:53,409 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 213
ERROR 2024-08-24 12:01:54,590 log Internal Server Error: /api/trainers/all/
ERROR 2024-08-24 12:01:55,944 basehttp "GET /api/trainers/all/ HTTP/1.1" 500 213
ERROR 2024-08-24 12:02:26,660 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-24 12:02:26,680 basehttp "GET /api/course-content/Trainer/?user_name=Trainer100 HTTP/1.1" 500 5757
ERROR 2024-08-24 17:39:43,431 views Error occurred in get_login function: 'function' object has no attribute 'objects'
ERROR 2024-08-24 17:39:43,443 log Internal Server Error: /api/get/login/
ERROR 2024-08-24 17:39:43,446 basehttp "GET /api/get/login/ HTTP/1.1" 500 29
ERROR 2024-08-24 17:40:14,912 views Error occurred in get_login function: 'function' object has no attribute 'objects'
ERROR 2024-08-24 17:40:14,918 log Internal Server Error: /api/get/login/
ERROR 2024-08-24 17:40:14,922 basehttp "GET /api/get/login/ HTTP/1.1" 500 29
ERROR 2024-08-24 17:40:38,045 views Error occurred in get_login function: 'function' object has no attribute 'objects'
ERROR 2024-08-24 17:40:38,565 log Internal Server Error: /api/get/login/
ERROR 2024-08-24 17:40:38,586 basehttp "GET /api/get/login/ HTTP/1.1" 500 5216
ERROR 2024-08-24 17:43:31,434 views Error occurred in get_login function: 'function' object has no attribute 'objects'
ERROR 2024-08-24 17:43:31,864 log Internal Server Error: /api/get/login/
ERROR 2024-08-24 17:43:31,882 basehttp "GET /api/get/login/ HTTP/1.1" 500 5216
ERROR 2024-08-24 17:45:11,831 views Error occurred in get_login function: 'function' object has no attribute 'objects'
ERROR 2024-08-24 17:45:12,047 log Internal Server Error: /api/get/login/
ERROR 2024-08-24 17:45:12,058 basehttp "GET /api/get/login/ HTTP/1.1" 500 5216
ERROR 2024-08-24 18:33:30,319 log Internal Server Error: /api/nondb-candidates/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 7481, in get_nondb_candidate
    ).values('user__username', 'user__password', 'dtm_upload').order_by('-id')  # Order by id in descending order
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1360, in values
    clone = self._values(*fields, **expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1355, in _values
    clone.query.set_values(fields)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 2473, in set_values
    self.names_to_path(f.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: college_id, college_id_id, dtm_upload, email_id, id, password, role, user_name
ERROR 2024-08-24 18:33:30,791 basehttp "GET /api/nondb-candidates/ HTTP/1.1" 500 121534
ERROR 2024-08-24 19:44:03,489 log Internal Server Error: /api/schedule-with-tests/2024-08-24/105/
ERROR 2024-08-24 19:44:03,995 basehttp "GET /api/schedule-with-tests/2024-08-24/105/ HTTP/1.1" 500 59
ERROR 2024-08-24 19:46:31,947 views Catch Key...: question_data_code_3
ERROR 2024-08-24 19:46:32,956 views -----Data From Cache----
ERROR 2024-08-24 19:46:35,809 views -----Data From Database----
ERROR 2024-08-25 16:15:05,697 log Internal Server Error: /api/Candidate/import_excel/
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'department_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\V_Project\LMS-New\backend\app\views.py", line 2152, in post
    df['department_id'] = df['department_id'].apply(get_department_id)
                          ~~^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\pandas\core\frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python312\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'department_id'
ERROR 2024-08-25 16:15:06,010 basehttp "POST /api/Candidate/import_excel/ HTTP/1.1" 500 113473
ERROR 2024-08-25 16:30:25,135 log Internal Server Error: /api/schedule-with-tests/2024-08-25/116/
ERROR 2024-08-25 16:30:25,212 basehttp "GET /api/schedule-with-tests/2024-08-25/116/ HTTP/1.1" 500 59
ERROR 2024-08-25 16:31:28,212 views Catch Key...: question_data_code_7
ERROR 2024-08-25 16:31:28,524 views -----Data From Cache----
ERROR 2024-08-25 16:31:30,743 views -----Data From Database----
ERROR 2024-08-25 16:32:22,425 views Catch Key...: question_data_code_6
ERROR 2024-08-25 16:32:22,598 views -----Data From Cache----
ERROR 2024-08-25 16:32:24,275 views -----Data From Database----
ERROR 2024-08-25 16:32:53,119 log Internal Server Error: /api/tests-answer-com/submit/
ERROR 2024-08-25 16:32:53,123 basehttp "POST /api/tests-answer-com/submit/ HTTP/1.1" 500 33
ERROR 2024-08-25 16:42:06,378 views Catch Key...: question_data_code_6
ERROR 2024-08-25 16:42:06,394 views -----Data From Cache----
ERROR 2024-08-27 14:57:08,542 views Catch Key...: question_data_code_3
ERROR 2024-08-27 14:57:09,202 views -----Data From Cache----
ERROR 2024-08-27 14:57:10,761 views -----Data From Database----
ERROR 2024-08-27 15:09:11,930 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\3249e50a-f7b3-4904-84fc-324e5a87144c.cpp
ERROR 2024-08-27 15:09:11,934 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\3249e50a-f7b3-4904-84fc-324e5a87144c
ERROR 2024-08-27 15:09:39,681 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\3249e50a-f7b3-4904-84fc-324e5a87144c.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\3249e50a-f7b3-4904-84fc-324e5a87144c'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:09:39,776 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\32...>
ERROR 2024-08-27 15:11:16,877 views Files Delete in Assets
ERROR 2024-08-27 15:11:16,879 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\db0bdfb6-bd79-4321-9f7c-ad2c3c44921b.cpp
ERROR 2024-08-27 15:11:16,880 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\db0bdfb6-bd79-4321-9f7c-ad2c3c44921b
ERROR 2024-08-27 15:11:32,458 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\db0bdfb6-bd79-4321-9f7c-ad2c3c44921b.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\db0bdfb6-bd79-4321-9f7c-ad2c3c44921b'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:11:32,619 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\db...>
ERROR 2024-08-27 15:11:32,669 views Files Delete in Assets
ERROR 2024-08-27 15:14:52,377 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\323059c8-bea0-4f92-8d54-66e2c59d2ce6.cpp
ERROR 2024-08-27 15:14:52,412 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\323059c8-bea0-4f92-8d54-66e2c59d2ce6
ERROR 2024-08-27 15:14:57,178 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\323059c8-bea0-4f92-8d54-66e2c59d2ce6.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\323059c8-bea0-4f92-8d54-66e2c59d2ce6'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:14:57,366 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\32...>
ERROR 2024-08-27 15:19:00,012 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp
ERROR 2024-08-27 15:19:00,016 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\a10aad64-0054-4c0c-a4ca-e43e9e6b5630
ERROR 2024-08-27 15:19:03,484 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp: In function 'int main()':\nD:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp:157:17: error: 'brea' was not declared in this scope\nD:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\a10aad64-0054-4c0c-a4ca-e43e9e6b5630.cpp:157:17: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:19:03,500 views Files Delete in Assets
ERROR 2024-08-27 15:19:03,536 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\ee4992f6-e995-47b8-a867-257c046d8641.cpp
ERROR 2024-08-27 15:19:03,545 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\ee4992f6-e995-47b8-a867-257c046d8641
ERROR 2024-08-27 15:19:04,933 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp: In function 'int main()':\nD:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp:157:17: error: 'brea' was not declared in this scope\nD:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\ee4992f6-e995-47b8-a867-257c046d8641.cpp:157:17: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:19:04,946 views Files Delete in Assets
ERROR 2024-08-27 15:19:25,911 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp
ERROR 2024-08-27 15:19:25,912 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\59baa9c1-c89e-418f-a023-ea71a18d084e
ERROR 2024-08-27 15:19:31,525 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp: In function 'int main()':\nD:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp:157:17: error: 'brea' was not declared in this scope\nD:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\59baa9c1-c89e-418f-a023-ea71a18d084e.cpp:157:17: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:19:31,589 views Files Delete in Assets
ERROR 2024-08-27 15:19:31,707 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp
ERROR 2024-08-27 15:19:31,771 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\ad904829-e13f-4b04-bdf3-035f64f41a9c
ERROR 2024-08-27 15:19:37,059 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp: In function 'int main()':\nD:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp:157:17: error: 'brea' was not declared in this scope\nD:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp:157:17: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\ad904829-e13f-4b04-bdf3-035f64f41a9c.cpp:157:17: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:19:37,635 views Files Delete in Assets
ERROR 2024-08-27 15:20:21,491 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\f2faf34f-7482-4e7b-9e16-b5630d361a54.cpp
ERROR 2024-08-27 15:20:21,499 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\f2faf34f-7482-4e7b-9e16-b5630d361a54
ERROR 2024-08-27 15:20:27,852 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\f2faf34f-7482-4e7b-9e16-b5630d361a54.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\f2faf34f-7482-4e7b-9e16-b5630d361a54'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\f2faf34f-7482-4e7b-9e16-b5630d361a54.cpp: In function 'void cleanup()':\nD:\\V_Project\\LMS-New\\backend\\assets\\f2faf34f-7482-4e7b-9e16-b5630d361a54.cpp:119:27: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\f2faf34f-7482-4e7b-9e16-b5630d361a54.cpp:119:27: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:20:27,896 views Files Delete in Assets
ERROR 2024-08-27 15:20:28,070 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\4eb4d102-f0fb-432b-9eaa-ee710a050c61.cpp
ERROR 2024-08-27 15:20:28,134 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\4eb4d102-f0fb-432b-9eaa-ee710a050c61
ERROR 2024-08-27 15:20:34,193 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\4eb4d102-f0fb-432b-9eaa-ee710a050c61.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\4eb4d102-f0fb-432b-9eaa-ee710a050c61'], returncode=1, stdout='', stderr="D:\\V_Project\\LMS-New\\backend\\assets\\4eb4d102-f0fb-432b-9eaa-ee710a050c61.cpp: In function 'void cleanup()':\nD:\\V_Project\\LMS-New\\backend\\assets\\4eb4d102-f0fb-432b-9eaa-ee710a050c61.cpp:119:27: error: expected '}' at end of input\nD:\\V_Project\\LMS-New\\backend\\assets\\4eb4d102-f0fb-432b-9eaa-ee710a050c61.cpp:119:27: error: expected '}' at end of input\n")
ERROR 2024-08-27 15:20:34,616 views Files Delete in Assets
ERROR 2024-08-27 15:22:15,118 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\1c7bedbf-e890-4d5a-8abd-5a69cddfd4ce.cpp
ERROR 2024-08-27 15:22:15,126 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\1c7bedbf-e890-4d5a-8abd-5a69cddfd4ce
ERROR 2024-08-27 15:22:22,920 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\1c7bedbf-e890-4d5a-8abd-5a69cddfd4ce.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\1c7bedbf-e890-4d5a-8abd-5a69cddfd4ce'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:22:23,041 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\1c...>
ERROR 2024-08-27 15:23:30,731 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\72ad64a8-15e4-4e66-a36b-0095d1c1b0f3.cpp
ERROR 2024-08-27 15:23:30,919 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\72ad64a8-15e4-4e66-a36b-0095d1c1b0f3
ERROR 2024-08-27 15:23:37,725 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\72ad64a8-15e4-4e66-a36b-0095d1c1b0f3.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\72ad64a8-15e4-4e66-a36b-0095d1c1b0f3'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:23:37,860 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\72...>
ERROR 2024-08-27 15:28:05,133 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\336b76c9-8a5c-48ab-b2f6-f380ecfa3050.cpp
ERROR 2024-08-27 15:28:05,736 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\336b76c9-8a5c-48ab-b2f6-f380ecfa3050
ERROR 2024-08-27 15:28:17,936 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\336b76c9-8a5c-48ab-b2f6-f380ecfa3050.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\336b76c9-8a5c-48ab-b2f6-f380ecfa3050'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:28:22,017 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\33...>
ERROR 2024-08-27 15:30:33,790 views C++ File Path Created...: D:\V_Project\LMS-New\backend\assets\e6ca2218-41a6-4c77-bb71-05cbd251e927.cpp
ERROR 2024-08-27 15:30:33,791 views C++ File Execute Path Created...: D:\V_Project\LMS-New\backend\assets\e6ca2218-41a6-4c77-bb71-05cbd251e927
ERROR 2024-08-27 15:30:37,185 views Compile Result...: CompletedProcess(args=['g++', 'D:\\V_Project\\LMS-New\\backend\\assets\\e6ca2218-41a6-4c77-bb71-05cbd251e927.cpp', '-o', 'D:\\V_Project\\LMS-New\\backend\\assets\\e6ca2218-41a6-4c77-bb71-05cbd251e927'], returncode=0, stdout='', stderr='')
ERROR 2024-08-27 15:30:37,406 views Process Result...: <Popen: returncode: None args: ['D:\\V_Project\\LMS-New\\backend\\assets\\e6...>
ERROR 2024-08-28 18:37:30,199 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-28 18:37:30,804 basehttp "GET /api/course-content/Trainer/?user_name=t1 HTTP/1.1" 500 54
ERROR 2024-08-28 18:37:36,826 log Internal Server Error: /api/course-content/Trainer/
ERROR 2024-08-28 18:37:37,197 basehttp "GET /api/course-content/Trainer/?user_name=t1 HTTP/1.1" 500 54
ERROR 2024-08-30 09:14:39,588 views Catch Key...: question_data_code_3
ERROR 2024-08-30 09:14:41,591 views -----Data From Cache----
ERROR 2024-08-30 09:14:43,696 views -----Data From Database----
ERROR 2024-08-30 09:56:42,271 views Catch Key...: question_data_code_3
ERROR 2024-08-30 09:56:43,019 views -----Data From Cache----
ERROR 2024-08-30 11:40:13,396 views Catch Key...: question_data_code_3
ERROR 2024-08-30 11:40:14,612 views -----Data From Cache----
ERROR 2024-08-30 11:40:21,456 views -----Data From Database----
ERROR 2024-08-30 13:13:41,320 views Catch Key...: question_data_code_3
ERROR 2024-08-30 13:13:42,126 views -----Data From Cache----
ERROR 2024-08-30 13:13:45,658 views -----Data From Database----
ERROR 2024-08-30 14:08:13,441 views Catch Key...: question_data_code_3
ERROR 2024-08-30 14:08:13,884 views -----Data From Cache----
ERROR 2024-08-30 15:38:11,367 views Catch Key...: question_data_code_3
ERROR 2024-08-30 15:38:11,776 views -----Data From Cache----
ERROR 2024-08-30 15:38:14,485 views -----Data From Database----
ERROR 2024-08-30 17:15:53,462 views Catch Key...: question_data_code_3
ERROR 2024-08-30 17:15:54,197 views -----Data From Cache----
ERROR 2024-08-30 17:15:59,737 views -----Data From Database----
ERROR 2024-08-30 19:17:16,924 views Catch Key...: question_data_code_3
ERROR 2024-08-30 19:17:18,417 views -----Data From Cache----
ERROR 2024-08-30 19:17:26,671 views -----Data From Database----
ERROR 2024-09-01 09:13:05,344 views Catch Key...: question_data_code_3
ERROR 2024-09-01 09:13:07,095 views -----Data From Cache----
ERROR 2024-09-01 09:13:13,019 views -----Data From Database----
ERROR 2024-09-01 10:09:03,820 views Catch Key...: question_data_code_3
ERROR 2024-09-01 10:09:04,902 views -----Data From Cache----
ERROR 2024-09-02 06:31:02,728 views Catch Key...: question_data_code_3
ERROR 2024-09-02 06:31:03,399 views -----Data From Cache----
ERROR 2024-09-02 06:31:05,562 views -----Data From Database----
ERROR 2024-09-02 06:51:30,762 views Catch Key...: question_data_code_3
ERROR 2024-09-02 06:51:31,067 views -----Data From Cache----
ERROR 2024-09-02 11:59:10,262 views Catch Key...: question_data_code_3
ERROR 2024-09-02 11:59:10,318 views -----Data From Cache----
ERROR 2024-09-02 11:59:10,854 views -----Data From Database----
